"""Named constants from the specs."""

from __future__ import annotations

DEFAULT_MAX_SIZE_CHARS = 2048

BOUNDARY_SCORE_THRESHOLD = 0.25

TARGET_STATEMENTS_PER_CHUNKLET = 3
STATEMENT_COST_FLOOR = 1e-6
STATEMENT_COST_SCALE = 0.5

MIN_Q25_WORDS = 1.0
STATEMENTS_AT_Q25 = 0.75
QUARTILE_GAP_STATEMENTS = 0.50

BOUNDARY_STRENGTH_HEADING = 1.00
BOUNDARY_STRENGTH_BLOCKQUOTE = 0.75
BOUNDARY_STRENGTH_PARAGRAPH = 0.50
BOUNDARY_STRENGTH_LIST = 0.25

TYPICAL_CHUNKLET_LOWER_QUANTILE = 0.15
TYPICAL_CHUNKLET_UPPER_QUANTILE = 0.85
HEADING_SPLIT_BEFORE_DIVISOR = 4.0
HEADING_SPLIT_AFTER_FORBID = 1.0

DEFAULT_PREAMBLE_FRACTION = 0.382

MAX_HEADING_LEVELS = 6
HEADING_PATH_SEPARATOR = "\n"
